---
title: "A Final Test!"
output:
  html_document:
    code_folding: "hide"
---

<br>

## Final Exercise

The file "DE_genes_unfiltered.csv" contains a list of differentially expressed genes from experiment on bacteria. 
Your task is the followng: to import the data, create additional columns, filter on some sepecified thresholds, and create a plot. 

The points below outline in more detail what should be done:

* Import the data using the `read.csv()` function
* Create a new column containing the absolute absolute fold change (Hint: use the `abs()` function)
* Filter the genes on the follow conditions:
  * Adjusted p-value less than or equal to 0.05
  * Absolute fold change greater than or equal to `log2(1.5)`

* Once the data has been filtered, create a plot with log2 fold change on the x-axis and adjusted p-value on the x-axis
  * NOTE: use the `-log10(adjusted_pvalue)` for the plot
  * Colour the points by adjusted p-value
  * Set the transparancy to 70% (ALL points)
  * Add a title to the plot, and change the axis and legend titles to be more "readable"

<br>

### Solution

```{r eval = FALSE}
DEGenes <- read.csv("./data/DE_genes_unfiltered.csv")

DEGenes_new <- DEGenes %>% 
  mutate(abs_l2fc = abs(log2FoldChange)) %>% 
  filter(adjusted_pvalue <= 0.05, abs_l2fc >= log2(1.5))

ggplot(DEGenes_new, aes(log2FoldChange, -log10(adjusted_pvalue), colour = log2FoldChange)) +
  geom_point(alpha = 0.7) +
  labs(title = "Plot of DE Genes", 
       x = "Log2 Fold Change", 
       y ="Adjusted P-Value (-log10)",
       colour = "Log2 Fold Change")

```

<br>
